Fix most strong mode errors in lib/; LineSplitter issue remains
dart-lang/scheduled_test pull request #33
Opened 2017-03-10 19:17 UTC by srawlins

Fixes #32 

Several issues to note during review:

* Schedule and TaskQueue take a type parameter. This is because TaskQueue.schedule is expected to take a function of T, the type that `task.runChild` returns a Future of. Hopefully this isn't like, an external, breaking change? If it is too invasive, let me know how else to fix. (Can maybe just use `as`, though dirty...)
* tossed the (deprecated) ChunkedConverter for Converter. 

Maybe others...

One more Strong mode issue remains. LineSplitter doesn't fit where it is... not sure how to fix right now.

2017-03-10 21:44 UTC, nex3 requested changes

2017-03-10 21:44 UTC, nex3 commented on lib/src/descriptor/file_descriptor.dart
> +  }
This change shouldn't be necessary with the latest `test`. You may need to increment `scheduled_test`'s constraint to get it, though.

2017-03-10 21:44 UTC, nex3 commented on lib/src/schedule.dart
> +class Schedule<T> {
This type is wrong. A schedule doesn't always use the same return value for every task—task return values are typed separately for each call to `schedule()`. So neither `Schedule` nor `TaskQueue` should have type parameters.

2017-03-10 21:44 UTC, nex3 commented on lib/scheduled_test.dart
> +Future<T> schedule<T>(T fn(), [String description]) =>
Make sure the SDK version only allows versions that support uncommented generic methods.

2017-03-10 21:44 UTC, nex3 commented on lib/src/task.dart
> +  Future<T> runChild(TaskBody fn, String description) {
The original type parameter was correct. `Task.runChild()` can return a different type than the `Task` itself returned.

2017-03-10 23:34 UTC, srawlins commented on lib/scheduled_test.dart
> +Future<T> schedule<T>(T fn(), [String description]) =>
Done. 1.22.0 required for FutureOr type.

2017-03-10 23:34 UTC, srawlins commented on lib/src/descriptor/file_descriptor.dart
> +  }
Done! Thanks Natalie for that catch.

2017-03-10 23:34 UTC, srawlins commented on lib/src/schedule.dart
> +class Schedule<T> {
Done

2017-03-10 23:34 UTC, srawlins commented on lib/src/task.dart
> +  Future<T> runChild(TaskBody fn, String description) {
Done

2017-03-10 23:36 UTC, srawlins commented
Thanks Natalie. If you have a hint on the LineSplitter issue, I'll take it!

Also let me know if I need to bump the CHANGELOG or the version in pubspec.

2017-03-10 23:50 UTC, nex3 requested changes
> Thanks Natalie. If you have a hint on the LineSplitter issue, I'll take it!

What's the error you're seeing?

> Also let me know if I need to bump the CHANGELOG or the version in pubspec.

Yes, please bump to the next minor version, and please add a CHANGELOG note about the strong mode fixes and about supporting new `test` APIs.

2017-03-10 23:50 UTC, nex3 commented on lib/src/task.dart
> +  Future<S> runChild<S>(TaskBody<S> fn, String description) {
I prefer to avoid using function types in public locations if possible, since it makes the documentation less direct.

2017-03-11 00:06 UTC, srawlins commented
Sorry, the new LineSplitter error is a bit different, since removing ChunkedConverter:

> [error] The argument type 'LineSplitter' can't be assigned to the parameter type 'Converter<String, dynamic>' at lib/scheduled_process.dart:199:41 (argument_type_not_assignable).

2017-03-11 00:06 UTC, nex3 commented
You might need to use `LineSplitter.bind()` instead of `.transform(LineSplitter)` somewhere...

2017-03-11 00:16 UTC, srawlins commented on lib/src/task.dart
> +  Future<S> runChild<S>(TaskBody<S> fn, String description) {
Done.

2017-03-11 00:16 UTC, srawlins commented
OK, I'll hold off on that fix.

2017-03-11 00:26 UTC, nex3 commented
Don't forget the pubspec + changelog!

2017-03-11 00:35 UTC, srawlins commented
Done

2017-03-11 00:37 UTC, merged

2017-03-11 00:37 UTC, nex3 commented
Thanks!